# Generated by Django 5.2.3 on 2025-06-24 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designation', to='gestion.match', verbose_name='Match'),
        ),
    ]
