# Generated by Django 5.2.3 on 2025-07-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adresse',
        ),
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.CharField(blank=True, choices=[('Tivaouane', 'Tivaouane'), ('Mboro', 'Mboro'), ('Meckhe', 'Meckhe'), ('Pambale', 'Pambale')], max_length=50, null=True),
        ),
    ]
