# Generated by Django 5.2.3 on 2025-07-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_user_adresse_user_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_ordre_present', models.BooleanField(default=False)),
                ('secouristes_present', models.BooleanField(default=False)),
                ('delegue_present', models.BooleanField(default=False)),
                ('match_joue', models.BooleanField(default=True)),
                ('motif_non_joue', models.TextField(blank=True, null=True)),
                ('jaunes_domicile', models.PositiveIntegerField(default=0)),
                ('rouges_domicile', models.PositiveIntegerField(default=0)),
                ('jaunes_exterieur', models.PositiveIntegerField(default=0)),
                ('rouges_exterieur', models.PositiveIntegerField(default=0)),
                ('buts_domicile', models.PositiveIntegerField(default=0)),
                ('buts_exterieur', models.PositiveIntegerField(default=0)),
                ('remplacements_domicile', models.TextField(blank=True, null=True)),
                ('remplacements_exterieur', models.TextField(blank=True, null=True)),
                ('remarques_arbitre', models.TextField(blank=True, null=True)),
                ('date_rapport', models.DateTimeField(auto_now_add=True)),
                ('arbitre_central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.arbitre')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.match')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementRemplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('domicile', 'Équipe domicile'), ('exterieur', 'Équipe extérieur')], max_length=20)),
                ('joueur_sortant', models.CharField(max_length=5)),
                ('joueur_entrant', models.CharField(max_length=5)),
                ('minute', models.PositiveIntegerField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacements', to='gestion.rapportmatch')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementBut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('domicile', 'Équipe domicile'), ('exterieur', 'Équipe extérieur')], max_length=20)),
                ('joueur_dossard', models.CharField(max_length=5)),
                ('minute', models.PositiveIntegerField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buts', to='gestion.rapportmatch')),
            ],
        ),
        migrations.CreateModel(
            name='SanctionDisciplinaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('domicile', 'Équipe domicile'), ('exterieur', 'Équipe extérieur')], max_length=20)),
                ('joueur_dossard', models.CharField(max_length=5)),
                ('type_carton', models.CharField(choices=[('jaune', '🟨 Avertissement'), ('rouge', '🟥 Expulsion')], max_length=10)),
                ('minute', models.PositiveIntegerField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='gestion.rapportmatch')),
            ],
        ),
    ]
