# Generated by Django 5.2.3 on 2025-07-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_evenementbut_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenementbut',
            options={'ordering': ['minute'], 'verbose_name': 'But', 'verbose_name_plural': 'Buts'},
        ),
        migrations.AlterModelOptions(
            name='evenementremplacement',
            options={'ordering': ['minute'], 'verbose_name': 'Remplacement', 'verbose_name_plural': 'Remplacements'},
        ),
        migrations.AlterModelOptions(
            name='sanctiondisciplinaire',
            options={'ordering': ['minute'], 'verbose_name': 'Sanction disciplinaire', 'verbose_name_plural': 'Sanctions disciplinaires'},
        ),
    ]
